---
abstract: "provides an XS boost for some of Type::Tiny's built-in type constraints"
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: '0.92'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 1
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.024, CPAN::Meta::Converter version 2.150010'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Type-Tiny-XS
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Type::Tiny::XS:
    file: lib/Type/Tiny/XS.pm
    version: '0.022'
  Type::Tiny::XS::Util:
    file: lib/Type/Tiny/XS/Util.pm
    version: '0.022'
requires:
  perl: '5.010001'
resources:
  Identifier: http://purl.org/NET/cpan-uri/dist/Type-Tiny-XS/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Type-Tiny-XS
  homepage: https://metacpan.org/release/Type-Tiny-XS
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-type-tiny-xs.git
version: '0.022'
x_contributors:
  - 'Graham Knop (HAARG) <haarg@cpan.org>'
  - 'Tomasz Konojacki (XENU) <xenu@cpan.org>'
  - 'Andrew Ruder (AERUDER) <aeruder@cpan.org>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
